-- =========================
-- ELIMINAR TABLAS SI EXISTEN
-- =========================
BEGIN
   FOR t IN (
      SELECT table_name 
      FROM user_tables 
      WHERE table_name IN 
            ('USUARIOS','CATEGORIAS','PRODUCTOS','SUBASTAS','PUJAS',
             'ESTADOS_ENVIO','DIRECCIONES_ENVIO','ENVIOS','TRANSACCIONES')
   ) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
EXCEPTION WHEN OTHERS THEN
   NULL;
END;
/
COMMIT;

-- =========================
-- CREAR TABLAS NUEVAS
-- =========================

-- Usuarios
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    correo VARCHAR2(150) UNIQUE NOT NULL,
    contrasena VARCHAR2(255) NOT NULL,
    rut VARCHAR2(12) UNIQUE NOT NULL,
    numero_telefono VARCHAR2(15),
    direccion VARCHAR2(500),
    presupuesto NUMBER(10,2) DEFAULT 5000.00,
    fecha_registro DATE DEFAULT SYSDATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO','INACTIVO','SUSPENDIDO'))
);

-- Categorias
CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR2(100) NOT NULL UNIQUE,
    descripcion VARCHAR2(500)
);


-- Productos
CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_producto VARCHAR2(200) NOT NULL,
    descripcion_producto CLOB,
    precio_inicial NUMBER(10,2) NOT NULL CHECK (precio_inicial > 0),
    precio_actual NUMBER(10,2) NOT NULL,
    imagen_url VARCHAR2(500),
    id_categoria NUMBER,
    id_usuario_propietario NUMBER NOT NULL,
    fecha_creacion DATE DEFAULT SYSDATE,
    estado_producto VARCHAR2(20) DEFAULT 'DISPONIBLE' CHECK (estado_producto IN ('DISPONIBLE','EN_SUBASTA','VENDIDO','RETIRADO')),
    CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria),
    CONSTRAINT fk_producto_propietario FOREIGN KEY (id_usuario_propietario) REFERENCES usuarios(id_usuario)
);

-- Subastas
CREATE TABLE subastas (
    id_subasta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    fecha_inicio DATE DEFAULT SYSDATE,
    fecha_fin DATE NOT NULL,
    duracion_segundos NUMBER DEFAULT 180,
    precio_final NUMBER(10,2),
    id_ganador NUMBER,
    estado_subasta VARCHAR2(20) DEFAULT 'ACTIVA' CHECK (estado_subasta IN ('PENDIENTE','ACTIVA','FINALIZADA','CANCELADA')),
    CONSTRAINT fk_subasta_producto FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    CONSTRAINT fk_subasta_ganador FOREIGN KEY (id_ganador) REFERENCES usuarios(id_usuario),
    CONSTRAINT chk_fecha_fin CHECK (fecha_fin > fecha_inicio)
);

-- Pujas
CREATE TABLE pujas (
    id_puja NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_subasta NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    monto_puja NUMBER(10,2) NOT NULL CHECK (monto_puja > 0),
    fecha_puja DATE DEFAULT SYSDATE,
    tipo_puja VARCHAR2(20) DEFAULT 'USUARIO' CHECK (tipo_puja IN ('USUARIO','BOT')),
    es_ganadora VARCHAR2(1) DEFAULT 'N' CHECK (es_ganadora IN ('S','N')),
    CONSTRAINT fk_puja_subasta FOREIGN KEY (id_subasta) REFERENCES subastas(id_subasta),
    CONSTRAINT fk_puja_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

-- Estados de envío
CREATE TABLE estados_envio (
    id_estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_estado VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(200)
);

-- Direcciones de envío
CREATE TABLE direcciones_envio (
    id_direccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calle VARCHAR2(200) NOT NULL,
    numero VARCHAR2(10),
    comuna VARCHAR2(100) NOT NULL,
    ciudad VARCHAR2(100) NOT NULL,
    region VARCHAR2(100) NOT NULL,
    codigo_postal VARCHAR2(10),
    referencias VARCHAR2(500)
);

-- Envios
CREATE TABLE envios (
    numero_envio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_subasta NUMBER NOT NULL,
    id_usuario_destinatario NUMBER NOT NULL,
    id_direccion_origen NUMBER NOT NULL,
    id_direccion_destino NUMBER NOT NULL,
    id_estado_envio NUMBER NOT NULL,
    fecha_envio DATE DEFAULT SYSDATE,
    fecha_entrega_estimada DATE,
    fecha_entrega_real DATE,
    empresa_transporte VARCHAR2(100),
    codigo_seguimiento VARCHAR2(100) UNIQUE,
    costo_envio NUMBER(8,2) DEFAULT 0,
    observaciones VARCHAR2(1000),
    CONSTRAINT fk_envio_subasta FOREIGN KEY (id_subasta) REFERENCES subastas(id_subasta),
    CONSTRAINT fk_envio_destinatario FOREIGN KEY (id_usuario_destinatario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_envio_origen FOREIGN KEY (id_direccion_origen) REFERENCES direcciones_envio(id_direccion),
    CONSTRAINT fk_envio_destino FOREIGN KEY (id_direccion_destino) REFERENCES direcciones_envio(id_direccion),
    CONSTRAINT fk_envio_estado FOREIGN KEY (id_estado_envio) REFERENCES estados_envio(id_estado)
);

-- Transacciones
CREATE TABLE transacciones (
    id_transaccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    tipo_transaccion VARCHAR2(20) NOT NULL CHECK (tipo_transaccion IN ('RECARGA','PUJA','REEMBOLSO')),
    monto NUMBER(10,2) NOT NULL,
    fecha_transaccion DATE DEFAULT SYSDATE,
    descripcion VARCHAR2(500),
    id_puja NUMBER,
    CONSTRAINT fk_transaccion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_transaccion_puja FOREIGN KEY (id_puja) REFERENCES pujas(id_puja)
);

COMMIT;


-- =============================================
-- SECUENCIAS (Alternativa a IDENTITY)
-- =============================================
-- Si prefieres usar secuencias tradicionales en lugar de IDENTITY:
/*
CREATE SEQUENCE seq_usuarios START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_productos START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_subastas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pujas START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_envios START WITH 1 INCREMENT BY 1;
*/

-- =============================================
-- DATOS INICIALES
-- =============================================

-- =============================================
-- INSERT PARA USUARIOS
-- =============================================
-- =============================================
-- INSERT PARA USUARIOS
-- =============================================
-- =============================================
-- INSERT PARA USUARIOS
-- =============================================
INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Juan Perez', 'juan.perez@email.com', 'hash1', '12345678-9', '987654321', 'Calle Falsa 123', 5000, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Maria Lopez', 'maria.lopez@email.com', 'hash2', '23456789-0', '987654322', 'Av. Siempre Viva 742', 4500, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Carlos Gomez', 'carlos.gomez@email.com', 'hash3', '34567890-1', '987654323', 'Calle Luna 12', 6000, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Ana Torres', 'ana.torres@email.com', 'hash4', '45678901-2', '987654324', 'Av. Sol 45', 5200, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Pedro Rojas', 'pedro.rojas@email.com', 'hash5', '56789012-3', '987654325', 'Calle Estrella 78', 4800, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Lucia Diaz', 'lucia.diaz@email.com', 'hash6', '67890123-4', '987654326', 'Av. Niebla 23', 5000, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Jorge Castillo', 'jorge.castillo@email.com', 'hash7', '78901234-5', '987654327', 'Calle Mar 56', 4700, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Sofia Herrera', 'sofia.herrera@email.com', 'hash8', '89012345-6', '987654328', 'Av. Cielo 89', 5100, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Diego Morales', 'diego.morales@email.com', 'hash9', '90123456-7', '987654329', 'Calle Sol 101', 4900, 'ACTIVO');

INSERT INTO usuarios (nombre, correo, contrasena, rut, numero_telefono, direccion, presupuesto, estado)
VALUES ('Valentina Cruz', 'valentina.cruz@email.com', 'hash10', '01234567-8', '987654330', 'Av. Luna 111', 5300, 'ACTIVO');


-- =============================================
-- INSERT PARA CATEGORIAS
-- =============================================
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Electrónicos','Dispositivos electrónicos y tecnología');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Gaming','Productos relacionados con videojuegos');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Deportes','Artículos deportivos y recreativos');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Coleccionables','Cartas, figuras y objetos coleccionables');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Hogar','Artículos para el hogar y decoración');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Ropa','Ropa y accesorios de moda');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Libros','Libros, cómics y revistas');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Belleza','Cosméticos y cuidado personal');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Automotriz','Accesorios y repuestos de autos');
INSERT INTO categorias (nombre_categoria, descripcion) VALUES ('Instrumentos','Instrumentos musicales y accesorios');


-- =============================================
-- INSERT PARA PRODUCTOS
-- =============================================
INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Smartphone X','Teléfono de última generación',700,700,'img1.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Electrónicos'),
        (SELECT id_usuario FROM usuarios WHERE correo='juan.perez@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Laptop Pro','Laptop para gaming',1200,1200,'img2.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Gaming'),
        (SELECT id_usuario FROM usuarios WHERE correo='maria.lopez@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Balón de fútbol','Balón oficial de torneo',50,50,'img3.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Deportes'),
        (SELECT id_usuario FROM usuarios WHERE correo='carlos.gomez@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Juego de cartas','Cartas coleccionables',30,30,'img4.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Coleccionables'),
        (SELECT id_usuario FROM usuarios WHERE correo='ana.torres@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Sofá 3 plazas','Sofá de cuero',800,800,'img5.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Hogar'),
        (SELECT id_usuario FROM usuarios WHERE correo='pedro.rojas@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Camisa casual','Camisa de algodón',25,25,'img6.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Ropa'),
        (SELECT id_usuario FROM usuarios WHERE correo='lucia.diaz@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Novela policíaca','Libro de misterio',15,15,'img7.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Libros'),
        (SELECT id_usuario FROM usuarios WHERE correo='jorge.castillo@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Perfume floral','Perfume unisex',60,60,'img8.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Belleza'),
        (SELECT id_usuario FROM usuarios WHERE correo='sofia.herrera@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Neumáticos deportivos','Juego de 4 neumáticos',400,400,'img9.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Automotriz'),
        (SELECT id_usuario FROM usuarios WHERE correo='diego.morales@email.com'),
        'DISPONIBLE');

INSERT INTO productos (nombre_producto, descripcion_producto, precio_inicial, precio_actual, imagen_url, id_categoria, id_usuario_propietario, estado_producto)
VALUES ('Guitarra acústica','Guitarra de madera',150,150,'img10.jpg',
        (SELECT id_categoria FROM categorias WHERE nombre_categoria='Instrumentos'),
        (SELECT id_usuario FROM usuarios WHERE correo='valentina.cruz@email.com'),
        'DISPONIBLE');
        
-- =============================================
-- SUBASTAS
-- =============================================
INSERT INTO subastas (id_producto, fecha_inicio, fecha_fin, estado_subasta)
VALUES (
  (SELECT id_producto FROM productos WHERE nombre_producto='Smartphone X'),
  TO_DATE('2025-10-01','YYYY-MM-DD'),
  TO_DATE('2025-10-10','YYYY-MM-DD'),
  'ACTIVA'
);

INSERT INTO subastas (id_producto, fecha_inicio, fecha_fin, estado_subasta)
VALUES (
  (SELECT id_producto FROM productos WHERE nombre_producto='Laptop Pro'),
  TO_DATE('2025-10-02','YYYY-MM-DD'),
  TO_DATE('2025-10-12','YYYY-MM-DD'),
  'ACTIVA'
);

INSERT INTO subastas (id_producto, fecha_inicio, fecha_fin, estado_subasta)
VALUES (
  (SELECT id_producto FROM productos WHERE nombre_producto='Balón de fútbol'),
  TO_DATE('2025-10-03','YYYY-MM-DD'),
  TO_DATE('2025-10-08','YYYY-MM-DD'),
  'ACTIVA'
);

-- =============================================
-- PUJAS
-- =============================================
-- Pujas de la subasta del Smartphone X
INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Smartphone X'),
  (SELECT id_usuario FROM usuarios WHERE correo='maria.lopez@email.com'),
  750
);

INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Smartphone X'),
  (SELECT id_usuario FROM usuarios WHERE correo='carlos.gomez@email.com'),
  800
);

-- Pujas de la subasta del Laptop Pro
INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Laptop Pro'),
  (SELECT id_usuario FROM usuarios WHERE correo='diego.morales@email.com'),
  1300
);

INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Laptop Pro'),
  (SELECT id_usuario FROM usuarios WHERE correo='valentina.cruz@email.com'),
  1350
);

-- Pujas de la subasta del Balón de fútbol
INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Balón de fútbol'),
  (SELECT id_usuario FROM usuarios WHERE correo='lucia.diaz@email.com'),
  60
);

INSERT INTO pujas (id_subasta, id_usuario, monto_puja)
VALUES (
  (SELECT id_subasta FROM subastas s JOIN productos p ON s.id_producto = p.id_producto WHERE p.nombre_producto='Balón de fútbol'),
  (SELECT id_usuario FROM usuarios WHERE correo='pedro.rojas@email.com'),
  70
);

-- =============================================
-- ENVÍOS
-- =============================================

-- Estados base para los envíos
INSERT INTO estados_envio (nombre_estado, descripcion)
VALUES ('Pendiente', 'El envío está pendiente de despacho');

INSERT INTO estados_envio (nombre_estado, descripcion)
VALUES ('En tránsito', 'El envío está en camino');

INSERT INTO estados_envio (nombre_estado, descripcion)
VALUES ('Entregado', 'El envío ha sido entregado exitosamente');

-- Direcciones de ejemplo
INSERT INTO direcciones_envio (calle, numero, comuna, ciudad, region, codigo_postal, referencias)
VALUES ('Av. del Sol', '100', 'Las Condes', 'Santiago', 'RM', '8320000', 'Cerca del parque Arauco');

INSERT INTO direcciones_envio (calle, numero, comuna, ciudad, region, codigo_postal, referencias)
VALUES ('Calle Luna', '555', 'Cerro Alegre', 'Valparaíso', 'V', '2360000', 'Frente a la plaza Victoria');


-- Insertar solo si no existen
MERGE INTO estados_envio e
USING (SELECT 'Pendiente' AS nombre_estado, 'El envío está pendiente de despacho' AS descripcion FROM dual) src
ON (e.nombre_estado = src.nombre_estado)
WHEN NOT MATCHED THEN
INSERT (nombre_estado, descripcion) VALUES (src.nombre_estado, src.descripcion);

MERGE INTO estados_envio e
USING (SELECT 'En tránsito' AS nombre_estado, 'El envío está en camino' AS descripcion FROM dual) src
ON (e.nombre_estado = src.nombre_estado)
WHEN NOT MATCHED THEN
INSERT (nombre_estado, descripcion) VALUES (src.nombre_estado, src.descripcion);

MERGE INTO estados_envio e
USING (SELECT 'Entregado' AS nombre_estado, 'El envío ha sido entregado exitosamente' AS descripcion FROM dual) src
ON (e.nombre_estado = src.nombre_estado)
WHEN NOT MATCHED THEN
INSERT (nombre_estado, descripcion) VALUES (src.nombre_estado, src.descripcion);

INSERT INTO direcciones_envio (calle, numero, comuna, ciudad, region, codigo_postal, referencias)
VALUES ('Av. del Sol', '100', 'Las Condes', 'Santiago', 'RM', '8320000', 'Cerca del parque Arauco');

INSERT INTO direcciones_envio (calle, numero, comuna, ciudad, region, codigo_postal, referencias)
VALUES ('Calle Luna', '555', 'Cerro Alegre', 'Valparaíso', 'V', '2360000', 'Frente a la plaza Victoria');



-- =============================================
-- TRANSACCIONES
-- =============================================

-- Transacción por puja ganadora (Smartphone X)
INSERT INTO transacciones (id_usuario, tipo_transaccion, monto, descripcion, id_puja)
VALUES (
  (SELECT id_usuario FROM usuarios WHERE correo='carlos.gomez@email.com'),
  'PUJA',
  800,
  'Compra de Smartphone X mediante subasta',
  (SELECT id_puja FROM pujas pj JOIN subastas sb ON pj.id_subasta=sb.id_subasta
   JOIN productos pr ON sb.id_producto=pr.id_producto
   WHERE pr.nombre_producto='Smartphone X' AND pj.monto_puja=800)
);

-- Transacción por puja ganadora (Laptop Pro)
INSERT INTO transacciones (id_usuario, tipo_transaccion, monto, descripcion, id_puja)
VALUES (
  (SELECT id_usuario FROM usuarios WHERE correo='valentina.cruz@email.com'),
  'PUJA',
  1350,
  'Compra de Laptop Pro mediante subasta',
  (SELECT id_puja FROM pujas pj JOIN subastas sb ON pj.id_subasta=sb.id_subasta
   JOIN productos pr ON sb.id_producto=pr.id_producto
   WHERE pr.nombre_producto='Laptop Pro' AND pj.monto_puja=1350)
);

-- Transacción por puja ganadora (Balón de fútbol)
INSERT INTO transacciones (id_usuario, tipo_transaccion, monto, descripcion, id_puja)
VALUES (
  (SELECT id_usuario FROM usuarios WHERE correo='pedro.rojas@email.com'),
  'PUJA',
  70,
  'Compra de Balón de fútbol mediante subasta',
  (SELECT id_puja FROM pujas pj JOIN subastas sb ON pj.id_subasta=sb.id_subasta
   JOIN productos pr ON sb.id_producto=pr.id_producto
   WHERE pr.nombre_producto='Balón de fútbol' AND pj.monto_puja=70)
);
